CREATE TABLE IF NOT EXISTS `teachers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `mobile` varchar(64) NOT NULL,
  `email` varchar(255) NOT NULL,
  `state` varchar(128) NOT NULL DEFAULT '',
  `city` varchar(128) NOT NULL DEFAULT '',
  `address` text,
  `ug_college` varchar(512) NOT NULL DEFAULT '',
  `pg_university` varchar(512) NOT NULL DEFAULT '',
  `qualification` varchar(512) NOT NULL DEFAULT '',
  `certifications` text,
  `subject_taught` varchar(255) NOT NULL DEFAULT '',
  `boards_taught` json DEFAULT NULL,
  `grades_taught` json DEFAULT NULL,
  `teacher_roles` json DEFAULT NULL,
  `current_location` varchar(255) NOT NULL DEFAULT '',
  `preferred_location` varchar(255) NOT NULL DEFAULT '',
  `area_of_interest` varchar(512) NOT NULL DEFAULT '',
  `current_salary` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total_experience` decimal(5,2) NOT NULL DEFAULT '0.00',
  `work_experience` json DEFAULT NULL,
  `skills` json DEFAULT NULL,
  `internal_notes` text,
  `resume_path` varchar(512) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `teachers_email_idx` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
